# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home -- notOnlyACoder
email: xiaocairush@gmail.com
description: 翻译技术 && 总结技巧 && 搬运请注明出处.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: notOnlyACoder
github_username:  xiaocairush

# Build settings
markdown: kramdown
